# @name loginOk
POST {{HOST}}/auth/login
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "password": "bobbob"
}

###

# @name loginBad
POST {{HOST}}/auth/login
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "password": "bobbob1"
}

